### ISSUE TITLE
Change textdomain to match the plugin slug

### ISSUE THREAD

**Issue by kasparsd** [nielsvr/comment-approved#1]
[WordPress.org will soon start supporting language packs for plugins](https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/) and one of the requirements for the feature is having the textdomain equal to the plugin slug. It should be `comment-approved` instead of `ca`.

**Comment by nielsvr** [comment]
Ah, wasn't aware of that. Will update in the next release. Thanks for the heads up. Got tons of feedback and good replies on the latest release.
